#! /usr/bin/env bash
. ~/Documents/passwords.txt

curl -d username=$IMGUR_USER -d password=$IMGUR_PASS -c /tmp/imgur_cookie.txt http://api.imgur.com/2/signin
imgur_hash=$(curl -F "image=@$1" -b /tmp/imgur_cookie.txt http://api.imgur.com/2/upload.xml | grep -v "version" | sed -e 's/<\/imgur_page.*//' -e 's/.*imgur_page>//' -e 's/.*\///')
curl -b /tmp/imgur_cookie.txt -d add_images=$imgur_hash http://api.imgur.com/2/account/albums/qPjvx &> /dev/null
rm /tmp/imgur_cookie.txt

echo http://derf.imgur.com/screenshots#$imgur_hash


