#! /usr/bin/env bash

set -x

MONITORS=$(xrandr | grep ' connected' | cut -f 1 -d ' ');
MONITOR_COUNT=$(echo "$MONITORS" | wc -l);
if [[ $MONITOR_COUNT -eq "3" ]]; then
    xrandr --output DP-2-1 --left-of eDP-1 --auto --primary --output DP-2-2 --left-of DP-2-1 --auto --output eDP-1 --auto
    notify-send "setting up 3 displays" -i preferences-desktop-display
elif [[ $MONITOR_COUNT -eq "2" ]]; then
    xrandr --output eDP-1 --auto --primary --output HDMI-2 --left-of eDP-1 --auto --output DP-2-1 --off --output DP-2-2 --off
    notify-send "setting up 2 display" -i preferences-desktop-display
elif [[ $MONITOR_COUNT -eq "1" ]]; then
    xrandr --output eDP-1 --auto --primary --output DP-2-1 --off --output DP-2-2 --off
    notify-send "setting up 1 display" -i preferences-desktop-display
fi
